name: Static Analysis

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cmake libsfml-dev

      - name: Configure CMake
        run: cmake -S src -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: |
          clang-tidy -p build $(find src -name '*.cpp') --header-filter='.*' > clang-tidy.log || true
          WARNINGS=$(grep -c "warning:" clang-tidy.log)
          echo "clang-tidy warnings: $WARNINGS"
          if [ "$WARNINGS" -gt 5 ]; then
            echo "❌ Too many warnings ($WARNINGS). Failing the build."
            exit 1
          else
            echo "✅ Warning count acceptable."
          fi
