name: Static Analysis

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cmake libsfml-dev

      - name: Configure CMake
        run: cmake -S src -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: |
          echo "🔍 Running clang-tidy..."
          
          # Run clang-tidy and save output
          clang-tidy -p build $(find src -name '*.cpp') --header-filter='.*' 2>&1 | tee clang-tidy-detailed.log
          
          WARNINGS=$(grep -c "warning:" clang-tidy-detailed.log || true)
          
          echo ""
          echo "📊 ANALYSIS SUMMARY"
          echo "===================="
          echo "⚠️  Total warnings: $WARNINGS"
          echo ""
          
          if [ "$WARNINGS" -gt 0 ]; then
            echo "🔍 WARNINGS BY FILE:"
            echo "===================="
            
            # Extract and group warnings by file
            CURRENT_FILE=""
            while IFS= read -r line; do
              if [[ "$line" =~ ^(.*\.cpp|.*\.h):[0-9]+:[0-9]+: ]]; then
                FILENAME=$(echo "$line" | cut -d: -f1)
                if [ "$FILENAME" != "$CURRENT_FILE" ]; then
                  CURRENT_FILE="$FILENAME"
                  echo ""
                  echo "📄 $CURRENT_FILE:"
                  echo "----------------------------------------"
                fi
                echo "$line" | sed 's/^[^:]*:[^:]*:[^:]*: //'
              fi
            done < clang-tidy-detailed.log
            echo ""
          fi
          
          if [ "$WARNINGS" -gt 5 ]; then
            echo "❌ Too many warnings ($WARNINGS). Failing the build."
            exit 1
          else
            echo "✅ Warning count acceptable."
          fi


